export const blogPosts = [
  {
    id: 1,
    title: "How to Compress PDF Files Without Losing Quality",
    excerpt:
      "Learn the best techniques to reduce PDF file size while maintaining document quality and readability. Discover professional methods used by experts.",
    content: "Full blog content here...",
    author: "Sarah Johnson",
    date: "December 15, 2024",
    readTime: "5 min read",
    image: "/blogs/1 (1).jpg",
    category: "Tips & Tricks",
    tags: ["PDF", "Compression", "Quality", "File Size"],
    featured: true,
  },
  {
    id: 2,
    title: "New PDF Security Features: Protect Your Documents",
    excerpt:
      "Discover our latest security enhancements including advanced encryption and digital signature options to keep your documents safe.",
    content: "Full blog content here...",
    author: "Mike Chen",
    date: "December 12, 2024",
    readTime: "3 min read",
    image: "/blogs/1 (1).png",
    category: "Updates",
    tags: ["Security", "Encryption", "Digital Signature"],
    featured: false,
  },
  {
    id: 3,
    title: "Converting PDFs to Office Formats: Complete Guide",
    excerpt:
      "Step-by-step guide on converting PDF files to Word, Excel, and PowerPoint with maximum accuracy and formatting preservation.",
    content: "Full blog content here...",
    author: "Emily Davis",
    date: "December 10, 2024",
    readTime: "7 min read",
    image: "/blogs/1 (2).jpg",
    category: "Tutorials",
    tags: ["Conversion", "Microsoft Office", "Word", "Excel"],
    featured: true,
  },
  {
    id: 4,
    title: "Best Practices for PDF Accessibility",
    excerpt:
      "Make your PDF documents accessible to everyone. Learn about screen readers, alt text, and proper document structure.",
    content: "Full blog content here...",
    author: "David Wilson",
    date: "December 8, 2024",
    readTime: "6 min read",
    image: "/blogs/1 (2).png",
    category: "Accessibility",
    tags: ["Accessibility", "Screen Readers", "Alt Text"],
    featured: false,
  },
  {
    id: 5,
    title: "PDF Forms: Creating Interactive Documents",
    excerpt:
      "Learn how to create fillable PDF forms with text fields, checkboxes, and digital signatures for better user experience.",
    content: "Full blog content here...",
    author: "Lisa Anderson",
    date: "December 5, 2024",
    readTime: "8 min read",
    image: "/blogs/1 (3).jpg",
    category: "Advanced",
    tags: ["Forms", "Interactive", "Digital Signature"],
    featured: false,
  },
  {
    id: 6,
    title: "Mobile PDF Editing: Tips and Tricks",
    excerpt:
      "Discover the best ways to edit PDF documents on your mobile device. Apps, techniques, and workflow optimization.",
    content: "Full blog content here...",
    author: "James Rodriguez",
    date: "December 3, 2024",
    readTime: "4 min read",
    image: "/blogs/1 (3).png",
    category: "Mobile",
    tags: ["Mobile", "Editing", "Apps", "Workflow"],
    featured: false,
  },
  {
    id: 7,
    title: "PDF Version Control: Managing Document Revisions",
    excerpt:
      "Learn professional techniques for managing PDF document versions, tracking changes, and collaborating effectively.",
    content: "Full blog content here...",
    author: "Anna Thompson",
    date: "December 1, 2024",
    readTime: "5 min read",
    image: "/blogs/1 (1).jpg",
    category: "Collaboration",
    tags: ["Version Control", "Collaboration", "Document Management"],
    featured: false,
  },
  {
    id: 8,
    title: "Optimizing PDFs for Web: Performance Tips",
    excerpt:
      "Speed up your website by optimizing PDF files for web delivery. Compression, embedding, and loading strategies.",
    content: "Full blog content here...",
    author: "Robert Kim",
    date: "November 28, 2024",
    readTime: "6 min read",
    image: "/blogs/1 (1).png",
    category: "Web Development",
    tags: ["Web", "Performance", "Optimization", "Loading"],
    featured: false,
  },
  {
    id: 9,
    title: "Legal Documents: PDF Standards and Compliance",
    excerpt:
      "Understanding PDF/A standards for legal documents, long-term archiving, and regulatory compliance requirements.",
    content: "Full blog content here...",
    author: "Jennifer Lee",
    date: "November 25, 2024",
    readTime: "9 min read",
    image: "/blogs/1 (2).jpg",
    category: "Legal",
    tags: ["Legal", "PDF/A", "Compliance", "Archiving"],
    featured: true,
  },
]

export const categories = [
  "All",
  "Tips & Tricks",
  "Updates",
  "Tutorials",
  "Accessibility",
  "Advanced",
  "Mobile",
  "Collaboration",
  "Web Development",
  "Legal",
]
